apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pantry-pal-health-check
spec:
  metrics:
    - name: endpoint-check
      interval: 10s
      count: 3
      failureLimit: 1
      provider:
        web:
          url: "http://pantry-pal-preview.opsera-pantry-pal-staging.svc.cluster.local"
          timeoutSeconds: 5
      successCondition: "result.statusCode == 200"
