apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-pantry-pal-staging
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - rollout-bluegreen.yaml
  - service-active.yaml
  - service-preview.yaml
  - ingress.yaml
  - analysis-template.yaml
images:
  - name: pantry-pal
    newName: PLACEHOLDER_ECR_URI
    newTag: v1.0.0
