apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-pantry-pal-qa
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - rollout-canary.yaml
  - service-stable.yaml
  - service-canary.yaml
  - ingress.yaml
  - analysis-template.yaml
images:
  - name: pantry-pal
    newName: PLACEHOLDER_ECR_URI
    newTag: v1.0.0
