app:
  name: pantry-pal
  tenant: opsera
  version: 1.0.0

cloud:
  provider: aws
  region: us-west-2
  region_short: usw2

infrastructure:
  hub_cluster: argocd-usw2
  spoke_cluster: opsera-usw2-np
  argocd_server: argocd-usw2.agent.opsera.dev
  domain: agent.opsera.dev

environments:
  - name: dev
    namespace: opsera-pantry-pal-dev
    hostname: pantry-pal-dev.agent.opsera.dev
    strategy: rolling
    replicas: 2
  - name: qa
    namespace: opsera-pantry-pal-qa
    hostname: pantry-pal-qa.agent.opsera.dev
    strategy: canary
    replicas: 2
    canary_steps: [20, 50, 100]
    monitoring: prometheus+newrelic
  - name: staging
    namespace: opsera-pantry-pal-staging
    hostname: pantry-pal-staging.agent.opsera.dev
    strategy: blue-green
    replicas: 2
    auto_promotion: false
    monitoring: health-check

integrations:
  monitoring:
    prometheus:
      url: http://prometheus-server.monitoring.svc.cluster.local:9090
    newrelic:
      region: us
      account_id_var: NEWRELIC_ACCOUNT_ID
  notifications:
    slack: enabled
  tracking:
    jira: enabled
