app:
  name: pantry-pal
  tenant: opsera
  version: 1.0.0

cloud:
  provider: aws
  region: us-west-2
  region_short: usw2

infrastructure:
  hub_cluster: argocd-usw2
  spoke_cluster: opsera-usw2-np
  argocd_server: argocd-usw2.agent.opsera.dev
  domain: agent.opsera.dev

environments:
  - name: dev
    namespace: opsera-pantry-pal-dev
    hostname: pantry-pal-dev.agent.opsera.dev
    strategy: rolling
    replicas: 2
